"""Bare and gauge-covariant formulation contracts and implementations."""

from aion.formulations.action import (
    OneElectronActionContraction,
    OneElectronActionFullContraction,
    OneElectronActionHistoryDirection,
    OneElectronActionMatrixDirection,
    one_electron_velocity_density,
    restricted_one_electron_action_directional_derivative,
    restricted_one_electron_action_full_directional_derivative,
    restricted_one_electron_action_history_directional_derivative,
    restricted_one_electron_action_value,
)
from aion.formulations.api import build_formulation
from aion.formulations.bare import BareLengthGauge, BareVelocityGauge
from aion.formulations.base import FormulationContext
from aion.formulations.covariant import P0, P0E1
from aion.formulations.events import apply_electric_kick, metric_unitary_impulse
from aion.formulations.exact_one_electron import (
    ExactDiscreteContinuity,
    ExactOneElectronModelContext,
    ExactOneElectronModelTriples,
    ExactPureGaugeActionDirection,
    ExactUniformElectricPower,
    OneElectronModelTriple,
    evaluate_exact_discrete_continuity,
    evaluate_exact_uniform_electric_power,
    exact_endpoint_link_action_direction,
    exact_internal_magnetic_action_direction,
    exact_magnetic_endpoint_action_direction,
    exact_magnetic_field_action_direction,
    exact_one_electron_model_triples,
    exact_pure_gauge_action_direction,
    exact_site_scalar_action_direction,
    exact_wilson_one_electron_triple,
    prepare_exact_one_electron_model_context,
)
from aion.formulations.kernels import (
    E1Tensors,
    MechanicalCurrent,
    P0Geometry,
    central_dipole_matrices,
    covariant_ambient_mechanical_current,
    density_derivative,
    e1_tensors,
    generic_mechanical_current,
    inverse_dressed_density,
    inverse_dressed_density_dot,
    p0_continuity_residual,
    p0_geometry,
    p0_graph_current,
    p0_pair_currents,
    p0_source_power,
    site_charge_derivatives,
    site_charges,
    uniform_mechanical_current,
)
from aion.formulations.types import (
    AODensity,
    CurrentLedger,
    EnergyLedger,
    EOMTriple,
    Formulation,
    FormulationSourceSample,
    InstantaneousEvaluation,
    PowerLedger,
    SourceSampling,
)

__all__ = [
    "P0",
    "P0E1",
    "AODensity",
    "BareLengthGauge",
    "BareVelocityGauge",
    "CurrentLedger",
    "E1Tensors",
    "EOMTriple",
    "EnergyLedger",
    "ExactDiscreteContinuity",
    "ExactOneElectronModelContext",
    "ExactOneElectronModelTriples",
    "ExactPureGaugeActionDirection",
    "ExactUniformElectricPower",
    "Formulation",
    "FormulationContext",
    "FormulationSourceSample",
    "InstantaneousEvaluation",
    "MechanicalCurrent",
    "OneElectronActionContraction",
    "OneElectronActionFullContraction",
    "OneElectronActionHistoryDirection",
    "OneElectronActionMatrixDirection",
    "OneElectronModelTriple",
    "P0Geometry",
    "PowerLedger",
    "SourceSampling",
    "apply_electric_kick",
    "build_formulation",
    "central_dipole_matrices",
    "covariant_ambient_mechanical_current",
    "density_derivative",
    "e1_tensors",
    "evaluate_exact_discrete_continuity",
    "evaluate_exact_uniform_electric_power",
    "exact_endpoint_link_action_direction",
    "exact_internal_magnetic_action_direction",
    "exact_magnetic_endpoint_action_direction",
    "exact_magnetic_field_action_direction",
    "exact_one_electron_model_triples",
    "exact_pure_gauge_action_direction",
    "exact_site_scalar_action_direction",
    "exact_wilson_one_electron_triple",
    "generic_mechanical_current",
    "inverse_dressed_density",
    "inverse_dressed_density_dot",
    "metric_unitary_impulse",
    "one_electron_velocity_density",
    "p0_continuity_residual",
    "p0_geometry",
    "p0_graph_current",
    "p0_pair_currents",
    "p0_source_power",
    "prepare_exact_one_electron_model_context",
    "restricted_one_electron_action_directional_derivative",
    "restricted_one_electron_action_full_directional_derivative",
    "restricted_one_electron_action_history_directional_derivative",
    "restricted_one_electron_action_value",
    "site_charge_derivatives",
    "site_charges",
    "uniform_mechanical_current",
]
