"""Aion real-time electronic dynamics prototypes."""

from .backends import CPUBackend, CuPyBackend, make_backend
from .cn_tddft import (
    CNPropagationRecord,
    LengthGaugeCNRTTDDFT,
    MidpointConvergenceError,
    SCEMRunSummary,
    SCEMStepResult,
)
from .fields import ContinuousWave, GaussianPulse, Sin2Pulse
from .gauge import (
    AOAnchors,
    PeierlsGeometry,
    UniformElectricGauge,
    UniformMagneticGauge,
)
from .linear_response import (
    HARTREE_TO_EV,
    Excitation,
    casida_excitations,
    excitation_by_index,
    load_excitations,
    lowest_active_excitation,
    save_excitations,
    transition_polarization,
)
from .matrix_models import (
    LinearOneBodyModel,
    SiteHubbardModel,
    density_from_coefficients,
    site_populations,
)
from .observables import (
    coefficient_orthonormality_error,
    electron_count,
    energy_derivative,
    electronic_energy,
    matrix_expectation,
    p0_continuity_residual,
    p0_directed_block,
    p0_dipole_derivative,
    p0_dipole_moment,
    p0_dipole_power,
    p0_graph_currents,
    p0_site_charge_derivative,
    p0_site_charges,
    p0_site_populations,
    p0_source_power,
)
from .p0_diagnostics import (
    P0Row,
    coefficient_derivative,
    density_derivative_from_coefficients,
    electric_field_for_power,
    model_energy,
    model_energy_derivative,
    p0_natom_from_rows,
    p0_row_series,
    record_p0_observables,
    summarize_p0_gauge_errors,
    trajectory_continuity_residual,
)
from .pyscf_p0 import PyscfP0LdaModel, PyscfP0Reference
from .rt_tddft import LengthGaugeRTTDDFT, PropagationRecord
from .spectrum import KickSpectrum, kick_spectrum, write_kick_spectrum_csv
from .variable_metric import (
    VariableMetricConvergenceError,
    VariableMetricSCEM,
    VariableMetricSCEMStepResult,
)

__all__ = [
    "AOAnchors",
    "CPUBackend",
    "CuPyBackend",
    "Excitation",
    "ContinuousWave",
    "GaussianPulse",
    "HARTREE_TO_EV",
    "KickSpectrum",
    "LengthGaugeCNRTTDDFT",
    "LengthGaugeRTTDDFT",
    "LinearOneBodyModel",
    "MidpointConvergenceError",
    "PeierlsGeometry",
    "CNPropagationRecord",
    "PropagationRecord",
    "PyscfP0LdaModel",
    "PyscfP0Reference",
    "P0Row",
    "SCEMStepResult",
    "SCEMRunSummary",
    "SiteHubbardModel",
    "Sin2Pulse",
    "UniformElectricGauge",
    "UniformMagneticGauge",
    "VariableMetricConvergenceError",
    "VariableMetricSCEM",
    "VariableMetricSCEMStepResult",
    "casida_excitations",
    "coefficient_orthonormality_error",
    "coefficient_derivative",
    "density_from_coefficients",
    "density_derivative_from_coefficients",
    "electron_count",
    "electric_field_for_power",
    "energy_derivative",
    "electronic_energy",
    "excitation_by_index",
    "kick_spectrum",
    "load_excitations",
    "lowest_active_excitation",
    "make_backend",
    "matrix_expectation",
    "model_energy",
    "model_energy_derivative",
    "p0_continuity_residual",
    "p0_directed_block",
    "p0_dipole_derivative",
    "p0_dipole_moment",
    "p0_dipole_power",
    "p0_graph_currents",
    "p0_natom_from_rows",
    "p0_row_series",
    "p0_site_charge_derivative",
    "p0_site_charges",
    "p0_site_populations",
    "p0_source_power",
    "record_p0_observables",
    "save_excitations",
    "site_populations",
    "summarize_p0_gauge_errors",
    "transition_polarization",
    "trajectory_continuity_residual",
    "write_kick_spectrum_csv",
]
