"""Versioned artifact schema and status-record contracts."""

from aion.io.schemas import (
    CASIDA_SCHEMA,
    CHECKPOINT_SCHEMA,
    KICK_SPECTRUM_SCHEMA,
    MAGNETIC_BENCHMARK_SCHEMA,
    REFERENCE_SCHEMA,
    SCHEMAS,
    SOURCE_HISTORY_SCHEMA,
    TRAJECTORY_SCHEMA,
    WILSON_CHECKPOINT_SCHEMA,
    WILSON_STATIONARY_STATE_SCHEMA,
    WILSON_TRAJECTORY_SCHEMA,
    ArtifactHeader,
    ArtifactKind,
    ArtifactSchema,
    stamp_artifact,
    validate_artifact,
    validate_open_artifact,
)
from aion.io.status import (
    STATUS_SCHEMA,
    STATUS_SCHEMA_VERSION,
    FailureSummary,
    RunPhase,
    RunStatus,
    dumps_status,
    loads_status,
    read_status,
)
from aion.io.transaction import publish_hdf5, write_dataset
from aion.io.versions import SchemaVersion

__all__ = [
    "CASIDA_SCHEMA",
    "CHECKPOINT_SCHEMA",
    "KICK_SPECTRUM_SCHEMA",
    "MAGNETIC_BENCHMARK_SCHEMA",
    "REFERENCE_SCHEMA",
    "SCHEMAS",
    "SOURCE_HISTORY_SCHEMA",
    "STATUS_SCHEMA",
    "STATUS_SCHEMA_VERSION",
    "TRAJECTORY_SCHEMA",
    "WILSON_CHECKPOINT_SCHEMA",
    "WILSON_STATIONARY_STATE_SCHEMA",
    "WILSON_TRAJECTORY_SCHEMA",
    "ArtifactHeader",
    "ArtifactKind",
    "ArtifactSchema",
    "FailureSummary",
    "RunPhase",
    "RunStatus",
    "SchemaVersion",
    "dumps_status",
    "loads_status",
    "publish_hdf5",
    "read_status",
    "stamp_artifact",
    "validate_artifact",
    "validate_open_artifact",
    "write_dataset",
]
