"""Prepared molecular references, operator bundles, and PySCF reconstruction."""

from aion.electronic_structure.adiabatic import (
    AdiabaticPureRKS,
    DFTInternalEnergy,
    DFTMatrixBuild,
    expectation,
    hermitian_part,
)
from aion.electronic_structure.ao_quadrature import (
    AOBlock,
    AOEvaluatorProvenance,
    AOGridKind,
    AOGridPolicy,
    AOQuadrature,
    AOQuadratureGrid,
    estimate_ao_block_bytes,
    prepare_ao_quadrature,
)
from aion.electronic_structure.data import (
    AnchorTopologyBundle,
    CoreOperatorBundle,
    DependencyVersions,
    E1OperatorBundle,
    GroundState,
    NuclearData,
    PreparedReference,
    QuadratureGrid,
)
from aion.electronic_structure.local_magnetic_matrices import (
    LocalPotentialMagneticResult,
    evaluate_local_potential_magnetic_matrices,
)
from aion.electronic_structure.local_potentials import (
    BoundLocalPotential,
    LocalPotentialIdentity,
    LocalPotentialProvider,
    NuclearAttractionProvider,
    ScaledLocalPotentialProvider,
    bind_local_potential,
)
from aion.electronic_structure.magnetic_matrices import (
    DirectGaugeOracle,
    GIAOOneElectronDerivatives,
    KineticExactSectors,
    KineticMagneticHierarchy,
    MagneticOneElectronResult,
    OneElectronLowerMatrices,
    ScalarMagneticHierarchy,
    estimate_magnetic_block_bytes,
    evaluate_magnetic_one_electron_matrices,
    pyscf_giao_one_electron_derivatives,
)
from aion.electronic_structure.operators import build_e1_operators, momentum_grid_residual
from aion.electronic_structure.pyscf_rks import (
    create_reference_workspace,
    prepare_pyscf_reference,
    reconstruct_mean_field,
    validate_reference_runtime,
)
from aion.electronic_structure.reference_io import load_reference_data, save_reference
from aion.electronic_structure.spatial_connection import (
    MagneticSpatialConnectionResult,
    SpatialConnectionDirectOracle,
    SpatialConnectionHierarchy,
    estimate_spatial_connection_block_bytes,
    evaluate_magnetic_spatial_connections,
)

__all__ = [
    "AOBlock",
    "AOEvaluatorProvenance",
    "AOGridKind",
    "AOGridPolicy",
    "AOQuadrature",
    "AOQuadratureGrid",
    "AdiabaticPureRKS",
    "AnchorTopologyBundle",
    "BoundLocalPotential",
    "CoreOperatorBundle",
    "DFTInternalEnergy",
    "DFTMatrixBuild",
    "DependencyVersions",
    "DirectGaugeOracle",
    "E1OperatorBundle",
    "GIAOOneElectronDerivatives",
    "GroundState",
    "KineticExactSectors",
    "KineticMagneticHierarchy",
    "LocalPotentialIdentity",
    "LocalPotentialMagneticResult",
    "LocalPotentialProvider",
    "MagneticOneElectronResult",
    "MagneticSpatialConnectionResult",
    "NuclearAttractionProvider",
    "NuclearData",
    "OneElectronLowerMatrices",
    "PreparedReference",
    "QuadratureGrid",
    "ScalarMagneticHierarchy",
    "ScaledLocalPotentialProvider",
    "SpatialConnectionDirectOracle",
    "SpatialConnectionHierarchy",
    "bind_local_potential",
    "build_e1_operators",
    "create_reference_workspace",
    "estimate_ao_block_bytes",
    "estimate_magnetic_block_bytes",
    "estimate_spatial_connection_block_bytes",
    "evaluate_local_potential_magnetic_matrices",
    "evaluate_magnetic_one_electron_matrices",
    "evaluate_magnetic_spatial_connections",
    "expectation",
    "hermitian_part",
    "load_reference_data",
    "momentum_grid_residual",
    "prepare_ao_quadrature",
    "prepare_pyscf_reference",
    "pyscf_giao_one_electron_derivatives",
    "reconstruct_mean_field",
    "save_reference",
    "validate_reference_runtime",
]
